/* Autogenerated file. Do not edit manually. */

import { defineComponent, Type as RecsType, World } from '@latticexyz/recs';

export function defineContractComponents(world: World) {
  return {
    Character: (() => {
      const name = 'Character';
      return defineComponent(
        world,
        {
          health: RecsType.Number,
          index: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Game: (() => {
      const name = 'Game';
      return defineComponent(
        world,
        {
          game_id: RecsType.Number,
          score: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Map: (() => {
      const name = 'Map';
      return defineComponent(
        world,
        {
          map_id: RecsType.Number,
          size: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    Tile: (() => {
      const name = 'Tile';
      return defineComponent(
        world,
        {
          _type: RecsType.Number,
          x: RecsType.Number,
          y: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    AuthStatus: (() => {
      const name = 'AuthStatus';
      return defineComponent(
        world,
        {
          is_authorized: RecsType.Boolean,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
    AuthRole: (() => {
      const name = 'AuthRole';
      return defineComponent(
        world,
        {
          id: RecsType.Number,
        },
        {
          metadata: {
            name: name,
          },
        }
      );
    })(),
  };
}
